### PR TITLE
Fix `--json` stats output and resource identifier cleaning

### LINKED ISSUE #316: Stats file only includes `index.html`
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
stats file only includes `index.html`

**If the current behavior is a bug, please provide the steps to reproduce.**
`preact build --json`

**What is the expected behavior?**
stats should include the whole bundle

**Please mention other relevant information.**
- node version
  **8.3.0**
- npm version
  **5.3.0**
- Operating system
  **Windows**
- preact cli
  **1.4.1**

### PR DESCRIPTION
**Pull request by developit**
This fixes #316.

### CODE REVIEW

File: src/lib/webpack/run-webpack.js [hunk 1]
```diff
@@ -146,19 +151,33 @@ export function writeJsonStats(stats) {
...
+	return str;
+}
 
-function stripBabelLoaderFromModuleNames(m) {
-	keysToNormalize.forEach(key => {
-		if (key in m) {
-			m[key] = stripBabelLoaderPrefix(m[key]);
+function stripLoaderFromModuleNames(m) {
+	for (let key in m) {
+		if (m.hasOwnProperty(key) && m[key]!=null && ~keysToNormalize.indexOf(key)) {
```
Comment (reznord) [inline src/lib/webpack/run-webpack.js]: Removing the `~` before `keysToNormalize.indexOf(key)` doesn't make a huge difference tho.
