### PR TITLE
Prefer c.modules (fixes #467)

### LINKED ISSUE #467: preact build --json fails with `TypeError: c.getModules is not a function`
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
`preact build --json` fails with `TypeError: c.getModules is not a function`

**If the current behaviour is a bug, please provide the steps to reproduce.**
I made sure I have latest preact-cli and webpack, etc.  I created a new preact-cli app with `preact create default my-project` ran `preact build --json` got error.

**What is the expected behaviour?**
to actually output build stats json file

**Please mention other relevant information.**
- Node version
v9.4.0
- npm version
5.6.0
- Operating system
MacOS 10.13.2 (17C205)
- webpack version
3.10.0
- CLI version
preact-cli 2.1.1
- Browser

### PR DESCRIPTION
**Pull request by developit**
This should fix #467.

### CODE REVIEW

File: src/lib/webpack/run-webpack.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ export function writeJsonStats(stats) {
 	function strip(stats) {
 		stats.modules.forEach(stripLoaderFromModuleNames);
 		stats.chunks.forEach(c => {
-			(c.mapModules!=null ? c.mapModules(Object) : c.getModules()).forEach(stripLoaderFromModuleNames);
+			(c.modules || (c.mapModules!=null ? c.mapModules(Object) : c.getModules())).forEach(stripLoaderFromModuleNames);
```
Comment (reznord) [inline src/lib/webpack/run-webpack.js]: `getModules()` is deprecated right? 

That's reason why we see that weird message when we run `preact build`
