### PR TITLE
Fix webpack config not matching win32 paths

### LINKED ISSUE #453: Some paths in webpack configs aren't matched on Windows
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I discovered this bug because routes are named `*.chunk.*.js` instead of `route-*.js` in the build output. This happens because Windows' backslash-delimited file paths (e.g. `C:\Users\me\dev\project\src\routes\home\index.js` aren't matched by these strings and regexes:

https://github.com/developit/preact-cli/blob/9eb46228922b05ecf88c0803a64f8fa5f04b2ab7/src/lib/webpack/webpack-client-config.js#L55-L58

There are probably more occurences of this throughout the webpack configs.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `preact create default test` on Windows
2. `cd test`, `npm install`
3. `npm run build`
4. In the `build` folder, route chunks aren't prefixed with `route-`

**What is the expected behavior?**
In this specific case, routes should be prefixed with `route-`, like on UNIX systems.
Generally, both `/` and `\`-delimited paths should be matched in webpack configs.

**Please mention other relevant information.**
- node version 8.9.1
- npm version 5.6.0
- Operating system Windows 10 1709

### PR DESCRIPTION
**Pull request by jgierer12**
Fixes #453 

AFAIK, this issue only occurred in this place, other webpack configs don't use unescaped paths. Nevertheless, I put the `normalizePath` function into `util.js` in case it has to be reused elsewhere in the future.

### CODE REVIEW

File: src/lib/webpack/webpack-client-config.js [hunk 1]
```diff
@@ -52,15 +55,15 @@ function clientConfig(env) {
...
+							if (!filename.includes('/routes/')) return false;
+							let relative = filename.replace(normalizePath(src), '');
+							return 'route-' + cleanFilename(relative);
 						},
 						formatName(filename) {
-							let relative = filename.replace(source('.'), '');
-							// strip out context dir & any file/ext suffix
-							return relative.replace(/(^\/(routes|components\/(routes|async))\/|(\/index)?\.js$)/g, '');
+							filename = normalizePath(filename);
+							let relative = filename.replace(normalizePath(source('.')), '');
```
Comment (jgierer12) [inline src/lib/webpack/webpack-client-config.js]: Any specific reason to use `source('.')` here instead of `src` like above?

**Comment by thangngoc89** [comment]
Hey @developit 
Could you take a look at this because you're the only person I know to code on Windows

**Comment by ForsakenHarmony** [comment]
What exactly is this a fix for?

File: src/lib/webpack/webpack-client-config.js [hunk 2]
```diff
@@ -52,15 +55,15 @@ function clientConfig(env) {
 					loader: resolve(__dirname, './async-component-loader'),
 					options: {
 						name(filename) {
-							let relative = filename.replace(src, '');
-							let isRoute = filename.indexOf('/routes/') >= 0;
-
-							return isRoute ? 'route-' + relative.replace(/(^\/(routes|components\/(routes|async))\/|(\/index)?\.js$)/g, '') : false;
+							filename = normalizePath(filename);
+							if (!filename.includes('/routes/')) return false;
+							let relative = filename.replace(normalizePath(src), '');
```
Comment (developit) [inline src/lib/webpack/webpack-client-config.js]: We might want to run this check on `relative` instead of `filename` - currently this will trigger a false positive if the repo is within a directory called "routes" (no clue why it would be, but still)

Comment (jgierer12) [reply src/lib/webpack/webpack-client-config.js]: ✅ https://github.com/developit/preact-cli/pull/454/commits/a6608c18d4351b6a9124ed45b4d060467eb4865d

File: src/lib/webpack/webpack-client-config.js (hunk 1 above)
Comment (ForsakenHarmony) [reply src/lib/webpack/webpack-client-config.js]: maybe noone ever changed it, not sure
